### ISSUE TITLE
Art Asset Standards

### ISSUE THREAD

**Issue by taggartdev** [johnying7/Five-Minute-Puzzle#11]
**As an** Artist

**I want** documentation describing art asset creation standards

**So that** anyone contributing art assets has a comprehensive guide to follow

**and** all art assets are uniform in format and file type.

**Acceptance Criteria**

- Per type of asset used:
  - List of accepted file types
  - List of requirements to be considered a complete asset
  - If necessary, instructions for creating specific assets
- File Naming Conventions
- Naming Conventions for copyrighted placeholders

**Comment by johnying7** [comment]
Any particular reason you've styled List of accepted file types, List of requirements to be considered a complete asset, etc the way you have? If you're trying to indent the bracket, just put two spaces before the - character.

**Comment by taggartdev** [comment]
> Any particular reason you've styled List of accepted file types, List of requirements to be considered a complete asset, etc the way you have? If you're trying to indent the bracket, just put two spaces before the - character.

Was struggling with formatting on mobile is all.

**Comment by taggartdev** [comment]
Doesn't really need to exist for this project, so I'm closing this issue.
