### ISSUE TITLE
Camera Controller

### ISSUE THREAD

**Issue by taggartdev** [johnying7/Five-Minute-Puzzle#9]
**Requirements**
#8 

**As a** Player
**I want** to control the camera's position
**So that** I can easily examine puzzles 

**Acceptance Criteria**

- Moving the mouse horizontally rotates the camera around the player.
- Moving the mouse vertically zooms the camera in when the it moves up, and zooms out when it moves down.
- Camera Zoom has defined minimum and maximum distances. 

I believe the pack-in Unity 3rd Person Controller will satisfy these criteria with little additional effort. If this is not the case, this Issue may be closed as invalid.

**Comment by johnying7** [comment]
Remove **and** line. Navigate with confidence is unnecessary.

**Comment by johnying7** [comment]
Obsolete and no longer needed. Sort of a duplicate issue for #8 Player Controlled Character.
